"""Generate the Condor Simplified Chinese catalog with an installed Argos model."""

import hashlib
import json
import re
from pathlib import Path

import argostranslate.sbd
import argostranslate.translate


def _catalog_entry_as_one_sentence(self, text):
    """Catalog entries are short UI strings and need no external SBD model."""
    return [text]


argostranslate.sbd.StanzaSentencizer.split_sentences = _catalog_entry_as_one_sentence


ROOT = Path(__file__).resolve().parents[1]
source = json.loads((ROOT / "scripts/i18n-source.json").read_text(encoding="utf-8"))
installed = argostranslate.translate.get_installed_languages()
english = next((lang for lang in installed if lang.code == "en"), None)
chinese = next((lang for lang in installed if lang.code.startswith("zh")), None)
if not english or not chinese:
    raise SystemExit("Argos en -> zh model is not installed")
translator = english.get_translation(chinese)

entries = []
for index, text in enumerate(source, 1):
    translated = translator.translate(text).strip()
    slug = re.sub(r"[^a-z0-9]+", ".", text.lower()).strip(".")[:42] or "text"
    digest = hashlib.sha1(text.encode()).hexdigest()[:8]
    entries.append({"id": f"generated.{slug}.{digest}", "en": text, "zh": translated})
    if index % 100 == 0:
        print(f"translated {index}/{len(source)}", flush=True)

output = (
    "// Generated by scripts/generate-i18n-offline.py.\n"
    "// Safety-critical terms are overridden in curated.ts.\n"
    "type GeneratedTranslationEntry = { id: string; en: string; zh: string };\n"
    f"export const generatedEntries: readonly GeneratedTranslationEntry[] = {json.dumps(entries, ensure_ascii=False, indent=2)};\n"
)
(ROOT / "src/i18n/generated.ts").write_text(output, encoding="utf-8")
print(f"wrote {len(entries)} entries", flush=True)
